### ISSUE TITLE
Add Location when creating a shop

### ISSUE THREAD

**Issue by tonyalaribe** [tonyalaribe/shop440#24]
Show a google map with javascript sdk, and have users select their location on the map. add a button so on mobile users can focus to their current location via gps. 

Also, store the location info in a format that bleve can understand:
https://godoc.org/github.com/blevesearch/bleve
location: [lat,long] (confirm in the documentation)

then also add the google places rendering of the location. eg city, country format. eg calabar, Nigeria

**Comment by spankie** [comment]
This has been done...
